<?php
// +----------------------------------------------------------------------
// | Created by linshan. 版权所有 @
// +----------------------------------------------------------------------
// | Copyright (c) 2020 All rights reserved.
// +----------------------------------------------------------------------
// | Technology changes the world . Accumulation makes people grow .
// +----------------------------------------------------------------------
// | Author: kaka梦很美 <1099013371@qq.com>
// +----------------------------------------------------------------------

namespace Raylin666\Framework\Command;

use Exception;
use Raylin666\Framework\Contract\ServerStateInterface;
use Raylin666\Framework\Helper\ServerStateHelper;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;

/**
 * Class ServerCommand
 * @package Raylin666\Framework\Command
 */
abstract class ServerCommand extends Command
{
    /**
     * Console configure
     */
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this->container->singleton(ServerStateInterface::class, function () {
            return new ServerStateHelper();
        });

        $this->addArgument('status', InputArgument::OPTIONAL, '服务状态类型 status | start | reload | stop');
        $this->addOption('daemon', 'd', InputOption::VALUE_NONE, '是否守护进程 --daemon | -d');
    }

    /**
     * 获取服务状态类型
     * @param InputInterface $input
     * @return string
     * @throws Exception
     */
    protected function setServerStatusType(InputInterface $input): string
    {
        $status = $input->getArgument('status') ?: ServerStateHelper::SERVER_TYPE_STATUS;
        $this->getServerStateInstance()->withServerStatusType($status);
        return $status;
    }

    /**
     * 是否守护进程运行
     * @param InputInterface $input
     * @return bool
     */
    protected function isDaemon(InputInterface $input): bool
    {
        $isDaemon = $input->hasParameterOption(['--daemon', '-d'], true) ? true : false;
        $this->getServerStateInstance()->withDaemon($isDaemon);
        return $isDaemon;
    }

    /**
     * @return ServerStateHelper
     */
    protected function getServerStateInstance(): ServerStateHelper
    {
        return $this->container->get(ServerStateInterface::class);
    }
}